MODEL (
  name silver.careplan_satusehat_data_clean,
  kind FULL,
  grain (name)
);

-- GENERATED by scripts/generate_parent_clean_models.py -- do not hand-edit
-- column lists here; change the source bronze model's `columns={...}`
-- schema, then regenerate.
--
-- Passthrough of bronze.careplan_satusehat_data. Only changes vs. raw bronze:
--   * TEXT columns: TRIM()'d, blank string ('') -> NULL. No casing changes,
--     no dedup, no joins, no business logic.
-- Dropped from bronze: api_response, payload_json (already flattened in models/silver/fhir_resources/; not duplicated here)

SELECT
    NULLIF(TRIM(name), '') AS name,
    NULLIF(TRIM(owner), '') AS owner,
    creation,
    modified,
    NULLIF(TRIM(modified_by), '') AS modified_by,
    docstatus,
    idx,
    NULLIF(TRIM(encounter_satusehat), '') AS encounter_satusehat,
    NULLIF(TRIM(patient_name), '') AS patient_name,
    NULLIF(TRIM(patient_ihs), '') AS patient_ihs,
    NULLIF(TRIM(practitioner_ihs), '') AS practitioner_ihs,
    NULLIF(TRIM(satusehat_encounter_id), '') AS satusehat_encounter_id,
    NULLIF(TRIM(title), '') AS title,
    NULLIF(TRIM(description), '') AS description,
    NULLIF(TRIM(status), '') AS status,
    NULLIF(TRIM(satusehat_id), '') AS satusehat_id
FROM bronze.tabCarePlan_SatuSehat
