MODEL (
  name silver.careplan_satusehat_data_submission_audit,
  kind VIEW,
  grain (name)
);

-- GENERATED by scripts/generate_submission_audit_models.py -- do not
-- hand-edit; change the source bronze model's `columns={...}` schema
-- and regenerate instead.
--
-- Post-submission audit view over bronze.careplan_satusehat_data. `payload_json` dropped
-- (irrelevant here -- see models/silver/fhir_resources/ for the outgoing
-- payload). `api_response` kept raw AND parsed: response_body auto-detects
-- which of the known api_response shapes this row uses (see generator
-- docstring), so this works regardless of which shape any given resource
-- turns out to use.

WITH parsed AS (
    SELECT
        *,
        CASE
        -- Shape D: 'STATUS CODE: N\n\n{json}' -- not valid JSON as a whole
        -- string, so pull out everything from the first '{' to the end.
        WHEN api_response LIKE 'STATUS CODE:%'
            THEN regexp_extract(api_response, '(\{.*)', 1)
        -- Shape B/C-element: {"status_code": N, "response": "<json-string>"}
        WHEN json_valid(api_response)
             AND json_extract_string(api_response, '$.response') IS NOT NULL
            THEN json_extract_string(api_response, '$.response')
        -- Shape A: already the body (FHIR resource or OperationOutcome)
        WHEN json_valid(api_response)
            THEN api_response
        ELSE NULL
    END AS response_body,
        CASE
        WHEN api_response LIKE 'STATUS CODE:%'
            THEN TRY_CAST(regexp_extract(api_response, 'STATUS CODE:\s*(\d+)', 1) AS INT)
        WHEN json_valid(api_response)
            THEN TRY_CAST(json_extract(api_response, '$.status_code') AS INT)
        ELSE NULL
    END AS submission_http_status
    FROM bronze.careplan_satusehat_data
    WHERE api_response IS NOT NULL
)
SELECT
    NULLIF(TRIM(name), '') AS name,
    NULLIF(TRIM(owner), '') AS owner,
    creation,
    modified,
    NULLIF(TRIM(modified_by), '') AS modified_by,
    docstatus,
    idx,
    NULLIF(TRIM(encounter_satusehat), '') AS encounter_satusehat,
    NULLIF(TRIM(patient_name), '') AS patient_name,
    NULLIF(TRIM(patient_ihs), '') AS patient_ihs,
    NULLIF(TRIM(practitioner_ihs), '') AS practitioner_ihs,
    NULLIF(TRIM(satusehat_encounter_id), '') AS satusehat_encounter_id,
    NULLIF(TRIM(title), '') AS title,
    NULLIF(TRIM(description), '') AS description,
    NULLIF(TRIM(status), '') AS status,
    NULLIF(TRIM(satusehat_id), '') AS satusehat_id,
    api_response,
    submission_http_status,
    json_extract_string(response_body, '$.resourceType') AS response_resource_type,
    (json_extract_string(response_body, '$.resourceType') = 'OperationOutcome') AS is_submission_error,
    CASE WHEN json_extract_string(response_body, '$.resourceType') = 'OperationOutcome'
         THEN json_extract_string(response_body, '$.issue[0].severity') END AS error_severity,
    CASE WHEN json_extract_string(response_body, '$.resourceType') = 'OperationOutcome'
         THEN json_extract_string(response_body, '$.issue[0].code') END AS error_code,
    CASE WHEN json_extract_string(response_body, '$.resourceType') = 'OperationOutcome'
         THEN json_extract_string(response_body, '$.issue[0].details.text') END AS error_message,
    CASE WHEN json_extract_string(response_body, '$.resourceType') = 'OperationOutcome'
         THEN json_extract_string(response_body, '$.issue[0].expression[0]') END AS error_expression,
    CASE WHEN json_extract_string(response_body, '$.resourceType') != 'OperationOutcome'
         THEN json_extract_string(response_body, '$.id') END AS submitted_resource_id,
    CASE WHEN json_extract_string(response_body, '$.resourceType') != 'OperationOutcome'
         THEN TRY_CAST(json_extract_string(response_body, '$.meta.lastUpdated') AS TIMESTAMP) END AS submitted_last_updated,
    CASE WHEN json_extract_string(response_body, '$.resourceType') != 'OperationOutcome'
         THEN json_extract_string(response_body, '$.meta.versionId') END AS submitted_version_id
FROM parsed
