MODEL (
  name silver.observation_satusehat_data_submission_audit,
  kind VIEW,
  grain (name, response_idx)
);

-- GENERATED by scripts/generate_submission_audit_models.py -- do not
-- hand-edit; change the source bronze model's `columns={...}` schema
-- and regenerate instead.
--
-- Post-submission audit view over bronze.observation_satusehat_data. Unlike the other 15
-- FHIR-resource audit models, this resource's api_response is a JSON ARRAY
-- (one {"status_code":N,"response":"<json-string>"} element per vital
-- sign submitted -- same reason payload_json is also an array here), so it
-- needs a json_each() unwrap before the same per-element shape detection
-- used everywhere else. Grain is (name, response_idx), mirroring the
-- (frappe_doc_name, observation_idx) grain already used in
-- models/silver/fhir_resources/observation.py.
-- `payload_json` dropped (see models/silver/fhir_resources/ for that).

WITH unwrapped AS (
    SELECT
        b.* EXCLUDE (payload_json),
        elem.key::INT AS response_idx,
        elem.value::VARCHAR AS response_element
    FROM bronze.tabObservation_SatuSehat AS b, json_each(TRY_CAST(b.api_response AS JSON)) AS elem
    WHERE b.api_response IS NOT NULL
      AND json_valid(b.api_response)
),
parsed AS (
    SELECT
        *,
        CASE
        -- Shape D: 'STATUS CODE: N\n\n{json}' -- not valid JSON as a whole
        -- string, so pull out everything from the first '{' to the end.
        WHEN response_element LIKE 'STATUS CODE:%'
            THEN regexp_extract(response_element, '(\{.*)', 1)
        -- Shape B/C-element: {"status_code": N, "response": "<json-string>"}
        WHEN json_valid(response_element)
             AND json_extract_string(response_element, '$.response') IS NOT NULL
            THEN json_extract_string(response_element, '$.response')
        -- Shape A: already the body (FHIR resource or OperationOutcome)
        WHEN json_valid(response_element)
            THEN response_element
        ELSE NULL
    END AS response_body,
        CASE
        WHEN response_element LIKE 'STATUS CODE:%'
            THEN TRY_CAST(regexp_extract(response_element, 'STATUS CODE:\s*(\d+)', 1) AS INT)
        WHEN json_valid(response_element)
            THEN TRY_CAST(json_extract(response_element, '$.status_code') AS INT)
        ELSE NULL
    END AS submission_http_status
    FROM unwrapped
)
SELECT
    NULLIF(TRIM(name), '') AS name,
    NULLIF(TRIM(owner), '') AS owner,
    creation,
    modified,
    NULLIF(TRIM(modified_by), '') AS modified_by,
    docstatus,
    idx,
    NULLIF(TRIM(encounter_satusehat), '') AS encounter_satusehat,
    NULLIF(TRIM(vital_signs), '') AS vital_signs,
    NULLIF(TRIM(patient), '') AS patient,
    NULLIF(TRIM(patient_name), '') AS patient_name,
    NULLIF(TRIM(patient_ihs), '') AS patient_ihs,
    NULLIF(TRIM(practitioner_ihs), '') AS practitioner_ihs,
    NULLIF(TRIM(satusehat_encounter_id), '') AS satusehat_encounter_id,
    NULLIF(TRIM(validation_status), '') AS validation_status,
    NULLIF(TRIM(satusehat_ids), '') AS satusehat_ids,
    api_response,
    response_idx,
    submission_http_status,
    json_extract_string(response_body, '$.resourceType') AS response_resource_type,
    (json_extract_string(response_body, '$.resourceType') = 'OperationOutcome') AS is_submission_error,
    CASE WHEN json_extract_string(response_body, '$.resourceType') = 'OperationOutcome'
         THEN json_extract_string(response_body, '$.issue[0].severity') END AS error_severity,
    CASE WHEN json_extract_string(response_body, '$.resourceType') = 'OperationOutcome'
         THEN json_extract_string(response_body, '$.issue[0].code') END AS error_code,
    CASE WHEN json_extract_string(response_body, '$.resourceType') = 'OperationOutcome'
         THEN json_extract_string(response_body, '$.issue[0].details.text') END AS error_message,
    CASE WHEN json_extract_string(response_body, '$.resourceType') = 'OperationOutcome'
         THEN json_extract_string(response_body, '$.issue[0].expression[0]') END AS error_expression,
    CASE WHEN json_extract_string(response_body, '$.resourceType') != 'OperationOutcome'
         THEN json_extract_string(response_body, '$.id') END AS submitted_resource_id,
    CASE WHEN json_extract_string(response_body, '$.resourceType') != 'OperationOutcome'
         THEN TRY_CAST(json_extract_string(response_body, '$.meta.lastUpdated') AS TIMESTAMP) END AS submitted_last_updated,
    CASE WHEN json_extract_string(response_body, '$.resourceType') != 'OperationOutcome'
         THEN json_extract_string(response_body, '$.meta.versionId') END AS submitted_version_id
FROM parsed
