# models/silver/fhir_resources/imaging_study.py
# GENERATED by scripts/generate_fhir_silver_models.py -- do not hand-edit column
# lists here; change flatquack/views/imaging_study.vd.json or the registry entry in
# models_dependencies/transformers/fhir_resource_registry.py, then regenerate.
#
# Flattens bronze.imaging_study_satusehat_data.payload_json in-memory via sqlonfhir,
# using flatquack/views/imaging_study.vd.json as the ViewDefinition. No intermediate
# files are read or written.
import pandas as pd
from sqlmesh import model
from sqlmesh.core.model import ModelKindName

from models_dependencies.transformers.fhir_flatten import flatten_bronze
from models_dependencies.transformers.fhir_resource_registry import FHIR_RESOURCE_REGISTRY

_CFG = FHIR_RESOURCE_REGISTRY["imaging_study"]


@model(
    "silver.imaging_study_fhir_resource",
    kind={
        "name": ModelKindName.INCREMENTAL_BY_TIME_RANGE,
        "time_column": "modified",
    },
    cron="@daily",
    grain='frappe_doc_name',
    columns={'frappe_doc_name': 'TEXT', 'modified': 'TIMESTAMP', 'docstatus': 'INT', 'servicerequest_satusehat': 'TEXT', 'patient_name': 'TEXT', 'patient_ihs': 'TEXT', 'satusehat_encounter_id': 'TEXT', 'satusehat_servicerequest_id': 'TEXT', 'satusehat_id': 'TEXT', 'fhir_id': 'TEXT', 'identifier_value': 'TEXT', 'status': 'TEXT', 'subject_ref': 'TEXT', 'encounter_ref': 'TEXT', 'started': 'TIMESTAMP', 'based_on_ref': 'TEXT', 'modality_code': 'TEXT', 'number_of_series': 'TEXT', 'number_of_instances': 'INT'},
)
def execute(context, start, end, execution_time, **kwargs):
    passthrough_source = _CFG["passthrough_source"]
    bronze_cols = ", ".join(
        f"{bronze_col} AS {alias}" if bronze_col != alias else bronze_col
        for alias, bronze_col in passthrough_source.items()
    )
    bronze_df = context.fetchdf(f"""
        SELECT {bronze_cols}, payload_json
        FROM {_CFG["bronze_table"]}
        WHERE modified BETWEEN '{start}' AND '{end}'
          AND payload_json IS NOT NULL
    """)

    if bronze_df.empty:
        return pd.DataFrame(columns=list(_CFG["passthrough_columns"]) + list(_CFG["fhir_columns"]))

    return flatten_bronze(
        bronze_df,
        vd_path=_CFG["vd_path"],
        passthrough_columns=list(_CFG["passthrough_columns"]),
        payload_col="payload_json",
        is_array_payload=_CFG["is_array_payload"],
        idx_column=_CFG["idx_column"],
        dtype_overrides={k: v for k, v in _CFG["fhir_columns"].items() if v != "TEXT"},
        column_renames=_CFG["column_renames"],
    )
