# models_dependencies/transformers/fhir_resource_registry.py
"""
Single source of truth for all 16 FHIR silver resources.

Each entry describes: which bronze table to read, which flatquack/views/*.vd.json
ViewDefinition to apply (unchanged -- these are already spec-compliant SQL-on-FHIR
ViewDefinitions, nothing was rewritten), which Frappe/bronze columns to carry
through untouched, any dtype overrides for flattened FHIR columns (mirrors the
explicit ::TYPE casts that used to live in the generated SQL), and any column
renames needed to keep the existing silver table schema stable (every resource's
FHIR `id` becomes `fhir_id`; `status` becomes `fhir_status` for Encounter and
MedicationDispense, where a Frappe-side status-like column already exists).

This replaces 16 near-duplicate hand-written SQL files with 16 thin model files
that all share one config + one engine (fhir_flatten.py). To onboard a new FHIR
resource: add a .vd.json under flatquack/views/, add one entry here, add one
model file that follows the same ~15-line pattern as the others in
models/silver/fhir_resources/, then run
`python scripts/generate_fhir_silver_models.py`.

is_array_payload=True is currently only needed for Observation, which is the
one resource where bronze.payload_json holds a JSON *array* of several bundled
Observation resources (e.g. multiple vitals submitted together) rather than a
single resource object. AllergyIntolerance / Specimen / MedicationDispense also
use json_each internally in the OLD SQL, but only to pick the "official"
identifier out of a repeating `identifier` element on a *single* resource --
that's expressed directly as `identifier.where(use='official').value.first()`
in their .vd.json and needs no special handling here.

NOTE on Encounter.class: the old FlatQuack-generated SQL had a documented bug
that treated Encounter.class as an array (FHIR R4 defines it as a single
Coding). flatquack/views/encounter.vd.json already uses the correct
`class.code` / `class.display` paths, so evaluating it directly with sqlonfhir
sidesteps that bug entirely -- nothing to fix here.
"""
FHIR_RESOURCE_REGISTRY = {   'allergy_intolerance': {   'bronze_table': 'bronze.tabAllergyIntolerance_SatuSehat',
                               'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/allergy_intolerance.vd.json',
                               'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                                          'modified': 'TIMESTAMP',
                                                          'docstatus': 'INT',
                                                          'encounter_satusehat': 'TEXT',
                                                          'patient_name': 'TEXT',
                                                          'patient_ihs': 'TEXT',
                                                          'practitioner_ihs': 'TEXT',
                                                          'satusehat_encounter_id': 'TEXT',
                                                          'frappe_status': 'TEXT',
                                                          'satusehat_id': 'TEXT'},
                               'passthrough_source': {   'frappe_doc_name': 'name',
                                                         'modified': 'modified',
                                                         'docstatus': 'docstatus',
                                                         'encounter_satusehat': 'encounter_satusehat',
                                                         'patient_name': 'patient_name',
                                                         'patient_ihs': 'patient_ihs',
                                                         'practitioner_ihs': 'practitioner_ihs',
                                                         'satusehat_encounter_id': 'satusehat_encounter_id',
                                                         'frappe_status': 'status',
                                                         'satusehat_id': 'satusehat_id'},
                               'is_array_payload': False,
                               'idx_column': None,
                               'fhir_columns': {   'fhir_id': 'TEXT',
                                                   'identifier_value': 'TEXT',
                                                   'clinical_status': 'TEXT',
                                                   'verification_status': 'TEXT',
                                                   'category': 'TEXT',
                                                   'code': 'TEXT',
                                                   'code_display': 'TEXT',
                                                   'code_text': 'TEXT',
                                                   'patient_ref': 'TEXT',
                                                   'encounter_ref': 'TEXT',
                                                   'recorder_ref': 'TEXT'},
                               'grain': ['frappe_doc_name'],
                               'model_name': 'silver.allergy_intolerance_fhir_resource',
                               'column_renames': {'id': 'fhir_id'}},
    'careplan': {   'bronze_table': 'bronze.tabCarePlan_SatuSehat',
                    'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/careplan.vd.json',
                    'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                               'modified': 'TIMESTAMP',
                                               'docstatus': 'INT',
                                               'encounter_satusehat': 'TEXT',
                                               'patient_name': 'TEXT',
                                               'patient_ihs': 'TEXT',
                                               'practitioner_ihs': 'TEXT',
                                               'satusehat_encounter_id': 'TEXT',
                                               'satusehat_id': 'TEXT'},
                    'passthrough_source': {   'frappe_doc_name': 'name',
                                              'modified': 'modified',
                                              'docstatus': 'docstatus',
                                              'encounter_satusehat': 'encounter_satusehat',
                                              'patient_name': 'patient_name',
                                              'patient_ihs': 'patient_ihs',
                                              'practitioner_ihs': 'practitioner_ihs',
                                              'satusehat_encounter_id': 'satusehat_encounter_id',
                                              'satusehat_id': 'satusehat_id'},
                    'is_array_payload': False,
                    'idx_column': None,
                    'fhir_columns': {   'fhir_id': 'TEXT',
                                        'status': 'TEXT',
                                        'intent': 'TEXT',
                                        'title': 'TEXT',
                                        'description': 'TEXT',
                                        'category_code': 'TEXT',
                                        'subject_ref': 'TEXT',
                                        'encounter_ref': 'TEXT',
                                        'author_ref': 'TEXT'},
                    'grain': ['frappe_doc_name'],
                    'model_name': 'silver.careplan_fhir_resource',
                    'column_renames': {'id': 'fhir_id'}},
    'composition': {   'bronze_table': 'bronze.tabComposition_SatuSehat',
                       'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/composition.vd.json',
                       'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                                  'modified': 'TIMESTAMP',
                                                  'docstatus': 'INT',
                                                  'encounter_satusehat': 'TEXT',
                                                  'composition_title': 'TEXT',
                                                  'patient_ihs': 'TEXT',
                                                  'practitioner_ihs': 'TEXT',
                                                  'satusehat_encounter_id': 'TEXT',
                                                  'satusehat_id': 'TEXT'},
                       'passthrough_source': {   'frappe_doc_name': 'name',
                                                 'modified': 'modified',
                                                 'docstatus': 'docstatus',
                                                 'encounter_satusehat': 'encounter_satusehat',
                                                 'composition_title': 'composition_title',
                                                 'patient_ihs': 'patient_ihs',
                                                 'practitioner_ihs': 'practitioner_ihs',
                                                 'satusehat_encounter_id': 'satusehat_encounter_id',
                                                 'satusehat_id': 'satusehat_id'},
                       'is_array_payload': False,
                       'idx_column': None,
                       'fhir_columns': {   'fhir_id': 'TEXT',
                                           'status': 'TEXT',
                                           'type_code': 'TEXT',
                                           'type_display': 'TEXT',
                                           'subject_ref': 'TEXT',
                                           'encounter_ref': 'TEXT',
                                           'date': 'TEXT',
                                           'author_ref': 'TEXT',
                                           'title': 'TEXT'},
                       'grain': ['frappe_doc_name'],
                       'model_name': 'silver.composition_fhir_resource',
                       'column_renames': {'id': 'fhir_id'}},
    'condition': {   'bronze_table': 'bronze.tabCondition_SatuSehat',
                     'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/condition.vd.json',
                     'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                                'modified': 'TIMESTAMP',
                                                'docstatus': 'INT',
                                                'encounter_satusehat': 'TEXT',
                                                'patient': 'TEXT',
                                                'patient_name': 'TEXT',
                                                'patient_ihs': 'TEXT',
                                                'satusehat_encounter_id': 'TEXT',
                                                'icd_code': 'TEXT',
                                                'diagnosis_display': 'TEXT',
                                                'validation_status': 'TEXT',
                                                'satusehat_id': 'TEXT'},
                     'passthrough_source': {   'frappe_doc_name': 'name',
                                               'modified': 'modified',
                                               'docstatus': 'docstatus',
                                               'encounter_satusehat': 'encounter_satusehat',
                                               'patient': 'patient',
                                               'patient_name': 'patient_name',
                                               'patient_ihs': 'patient_ihs',
                                               'satusehat_encounter_id': 'satusehat_encounter_id',
                                               'icd_code': 'icd_code',
                                               'diagnosis_display': 'diagnosis_display',
                                               'validation_status': 'validation_status',
                                               'satusehat_id': 'satusehat_id'},
                     'is_array_payload': False,
                     'idx_column': None,
                     'fhir_columns': {   'fhir_id': 'TEXT',
                                         'clinical_status': 'TEXT',
                                         'category_code': 'TEXT',
                                         'code': 'TEXT',
                                         'code_display': 'TEXT',
                                         'subject_ref': 'TEXT',
                                         'subject_display': 'TEXT',
                                         'encounter_ref': 'TEXT'},
                     'grain': ['frappe_doc_name'],
                     'model_name': 'silver.condition_fhir_resource',
                     'column_renames': {'id': 'fhir_id'}},
    'diagnostic_report': {   'bronze_table': 'bronze.tabDiagnosticReport_SatuSehat',
                             'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/diagnostic_report.vd.json',
                             'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                                        'modified': 'TIMESTAMP',
                                                        'docstatus': 'INT',
                                                        'encounter_satusehat': 'TEXT',
                                                        'servicerequest_satusehat': 'TEXT',
                                                        'specimen_satusehat': 'TEXT',
                                                        'observation_satusehat': 'TEXT',
                                                        'patient_name': 'TEXT',
                                                        'patient_ihs': 'TEXT',
                                                        'practitioner_ihs': 'TEXT',
                                                        'satusehat_id': 'TEXT'},
                             'passthrough_source': {   'frappe_doc_name': 'name',
                                                       'modified': 'modified',
                                                       'docstatus': 'docstatus',
                                                       'encounter_satusehat': 'encounter_satusehat',
                                                       'servicerequest_satusehat': 'servicerequest_satusehat',
                                                       'specimen_satusehat': 'specimen_satusehat',
                                                       'observation_satusehat': 'observation_satusehat',
                                                       'patient_name': 'patient_name',
                                                       'patient_ihs': 'patient_ihs',
                                                       'practitioner_ihs': 'practitioner_ihs',
                                                       'satusehat_id': 'satusehat_id'},
                             'is_array_payload': False,
                             'idx_column': None,
                             'fhir_columns': {   'fhir_id': 'TEXT',
                                                 'status': 'TEXT',
                                                 'category_code': 'TEXT',
                                                 'code': 'TEXT',
                                                 'code_display': 'TEXT',
                                                 'subject_ref': 'TEXT',
                                                 'encounter_ref': 'TEXT',
                                                 'effective_datetime': 'TEXT',
                                                 'issued': 'TIMESTAMP',
                                                 'performer_ref': 'TEXT',
                                                 'based_on_ref': 'TEXT',
                                                 'conclusion_code': 'TEXT'},
                             'grain': ['frappe_doc_name'],
                             'model_name': 'silver.diagnostic_report_fhir_resource',
                             'column_renames': {'id': 'fhir_id'}},
    'encounter': {   'bronze_table': 'bronze.tabEncounter_SatuSehat',
                     'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/encounter.vd.json',
                     'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                                'modified': 'TIMESTAMP',
                                                'docstatus': 'INT',
                                                'patient': 'TEXT',
                                                'patient_name': 'TEXT',
                                                'patient_ihs': 'TEXT',
                                                'practitioner': 'TEXT',
                                                'practitioner_name': 'TEXT',
                                                'practitioner_ihs': 'TEXT',
                                                'start_time': 'TIMESTAMP',
                                                'organization_id': 'TEXT',
                                                'location_id': 'TEXT',
                                                'satusehat_id': 'TEXT',
                                                'frappe_status': 'TEXT'},
                     'passthrough_source': {   'frappe_doc_name': 'name',
                                               'modified': 'modified',
                                               'docstatus': 'docstatus',
                                               'patient': 'patient',
                                               'patient_name': 'patient_name',
                                               'patient_ihs': 'patient_ihs',
                                               'practitioner': 'practitioner',
                                               'practitioner_name': 'practitioner_name',
                                               'practitioner_ihs': 'practitioner_ihs',
                                               'start_time': 'start_time',
                                               'organization_id': 'organization_id',
                                               'location_id': 'location_id',
                                               'satusehat_id': 'satusehat_id',
                                               'frappe_status': 'status'},
                     'is_array_payload': False,
                     'idx_column': None,
                     'fhir_columns': {   'fhir_id': 'TEXT',
                                         'identifier_value': 'TEXT',
                                         'fhir_status': 'TEXT',
                                         'class_code': 'TEXT',
                                         'class_display': 'TEXT',
                                         'subject_ref': 'TEXT',
                                         'subject_display': 'TEXT',
                                         'period_start': 'TEXT',
                                         'period_end': 'TIMESTAMP',
                                         'location_ref': 'TEXT',
                                         'service_provider_ref': 'TEXT'},
                     'grain': ['frappe_doc_name'],
                     'model_name': 'silver.encounter_fhir_resource',
                     'column_renames': {'id': 'fhir_id', 'status': 'fhir_status'}},
    'episode_of_care': {   'bronze_table': 'bronze.tabEpisodeOfCare_SatuSehat',
                           'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/episode_of_care.vd.json',
                           'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                                      'modified': 'TIMESTAMP',
                                                      'docstatus': 'INT',
                                                      'encounter_satusehat': 'TEXT',
                                                      'patient_name': 'TEXT',
                                                      'patient_ihs': 'TEXT',
                                                      'satusehat_id': 'TEXT'},
                           'passthrough_source': {   'frappe_doc_name': 'name',
                                                     'modified': 'modified',
                                                     'docstatus': 'docstatus',
                                                     'encounter_satusehat': 'encounter_satusehat',
                                                     'patient_name': 'patient_name',
                                                     'patient_ihs': 'patient_ihs',
                                                     'satusehat_id': 'satusehat_id'},
                           'is_array_payload': False,
                           'idx_column': None,
                           'fhir_columns': {   'fhir_id': 'TEXT',
                                               'status': 'TEXT',
                                               'identifier_value': 'TEXT',
                                               'type_code': 'TEXT',
                                               'patient_ref': 'TEXT',
                                               'managing_organization_ref': 'TEXT',
                                               'period_start': 'TIMESTAMP'},
                           'grain': ['frappe_doc_name'],
                           'model_name': 'silver.episode_of_care_fhir_resource',
                           'column_renames': {'id': 'fhir_id'}},
    'imaging_study': {   'bronze_table': 'bronze.tabImagingStudy_SatuSehat',
                         'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/imaging_study.vd.json',
                         'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                                    'modified': 'TIMESTAMP',
                                                    'docstatus': 'INT',
                                                    'servicerequest_satusehat': 'TEXT',
                                                    'patient_name': 'TEXT',
                                                    'patient_ihs': 'TEXT',
                                                    'satusehat_encounter_id': 'TEXT',
                                                    'satusehat_servicerequest_id': 'TEXT',
                                                    'satusehat_id': 'TEXT'},
                         'passthrough_source': {   'frappe_doc_name': 'name',
                                                   'modified': 'modified',
                                                   'docstatus': 'docstatus',
                                                   'servicerequest_satusehat': 'servicerequest_satusehat',
                                                   'patient_name': 'patient_name',
                                                   'patient_ihs': 'patient_ihs',
                                                   'satusehat_encounter_id': 'satusehat_encounter_id',
                                                   'satusehat_servicerequest_id': 'satusehat_servicerequest_id',
                                                   'satusehat_id': 'satusehat_id'},
                         'is_array_payload': False,
                         'idx_column': None,
                         'fhir_columns': {   'fhir_id': 'TEXT',
                                             'identifier_value': 'TEXT',
                                             'status': 'TEXT',
                                             'subject_ref': 'TEXT',
                                             'encounter_ref': 'TEXT',
                                             'started': 'TIMESTAMP',
                                             'based_on_ref': 'TEXT',
                                             'modality_code': 'TEXT',
                                             'number_of_series': 'TEXT',
                                             'number_of_instances': 'INT'},
                         'grain': ['frappe_doc_name'],
                         'model_name': 'silver.imaging_study_fhir_resource',
                         'column_renames': {'id': 'fhir_id'}},
    'immunization': {   'bronze_table': 'bronze.tabImmunization_SatuSehat',
                        'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/immunization.vd.json',
                        'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                                   'modified': 'TIMESTAMP',
                                                   'docstatus': 'INT',
                                                   'encounter_satusehat': 'TEXT',
                                                   'patient_name': 'TEXT',
                                                   'patient_ihs': 'TEXT',
                                                   'practitioner_ihs': 'TEXT',
                                                   'satusehat_encounter_id': 'TEXT',
                                                   'satusehat_id': 'TEXT'},
                        'passthrough_source': {   'frappe_doc_name': 'name',
                                                  'modified': 'modified',
                                                  'docstatus': 'docstatus',
                                                  'encounter_satusehat': 'encounter_satusehat',
                                                  'patient_name': 'patient_name',
                                                  'patient_ihs': 'patient_ihs',
                                                  'practitioner_ihs': 'practitioner_ihs',
                                                  'satusehat_encounter_id': 'satusehat_encounter_id',
                                                  'satusehat_id': 'satusehat_id'},
                        'is_array_payload': False,
                        'idx_column': None,
                        'fhir_columns': {   'fhir_id': 'TEXT',
                                            'status': 'TEXT',
                                            'vaccine_code': 'TEXT',
                                            'vaccine_display': 'TEXT',
                                            'patient_ref': 'TEXT',
                                            'encounter_ref': 'TEXT',
                                            'occurrence_datetime': 'TIMESTAMP',
                                            'primary_source': 'BOOLEAN',
                                            'lot_number': 'TEXT',
                                            'expiration_date': 'DATE',
                                            'performer_ref': 'TEXT',
                                            'reason_code': 'TEXT'},
                        'grain': ['frappe_doc_name'],
                        'model_name': 'silver.immunization_fhir_resource',
                        'column_renames': {'id': 'fhir_id'}},
    'medication_dispense': {   'bronze_table': 'bronze.tabMedicationDispense_SatuSehat',
                               'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/medication_dispense.vd.json',
                               'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                                          'modified': 'TIMESTAMP',
                                                          'docstatus': 'INT',
                                                          'medication_request_satusehat': 'TEXT',
                                                          'patient_name': 'TEXT',
                                                          'patient_ihs': 'TEXT',
                                                          'practitioner_ihs': 'TEXT',
                                                          'satusehat_encounter_id': 'TEXT',
                                                          'frappe_status': 'TEXT'},
                               'passthrough_source': {   'frappe_doc_name': 'name',
                                                         'modified': 'modified',
                                                         'docstatus': 'docstatus',
                                                         'medication_request_satusehat': 'medication_request_satusehat',
                                                         'patient_name': 'patient_name',
                                                         'patient_ihs': 'patient_ihs',
                                                         'practitioner_ihs': 'practitioner_ihs',
                                                         'satusehat_encounter_id': 'satusehat_encounter_id',
                                                         'frappe_status': 'status'},
                               'is_array_payload': False,
                               'idx_column': None,
                               'fhir_columns': {   'fhir_id': 'TEXT',
                                                   'identifier_value': 'TEXT',
                                                   'fhir_status': 'TEXT',
                                                   'medication_ref': 'TEXT',
                                                   'subject_ref': 'TEXT',
                                                   'context_ref': 'TEXT',
                                                   'when_handed_over': 'TIMESTAMP',
                                                   'authorizing_prescription_ref': 'TEXT',
                                                   'dosage_text': 'TEXT'},
                               'grain': ['frappe_doc_name'],
                               'model_name': 'silver.medication_dispense_fhir_resource',
                               'column_renames': {'id': 'fhir_id', 'status': 'fhir_status'}},
    'medication_statement': {   'bronze_table': 'bronze.tabMedicationStatement_SatuSehat',
                                'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/medication_statement.vd.json',
                                'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                                           'modified': 'TIMESTAMP',
                                                           'docstatus': 'INT',
                                                           'encounter_satusehat': 'TEXT',
                                                           'patient_name': 'TEXT',
                                                           'patient_ihs': 'TEXT',
                                                           'satusehat_encounter_id': 'TEXT',
                                                           'item_code': 'TEXT',
                                                           'satusehat_id': 'TEXT'},
                                'passthrough_source': {   'frappe_doc_name': 'name',
                                                          'modified': 'modified',
                                                          'docstatus': 'docstatus',
                                                          'encounter_satusehat': 'encounter_satusehat',
                                                          'patient_name': 'patient_name',
                                                          'patient_ihs': 'patient_ihs',
                                                          'satusehat_encounter_id': 'satusehat_encounter_id',
                                                          'item_code': 'item_code',
                                                          'satusehat_id': 'satusehat_id'},
                                'is_array_payload': False,
                                'idx_column': None,
                                'fhir_columns': {   'fhir_id': 'TEXT',
                                                    'status': 'TEXT',
                                                    'category_code': 'TEXT',
                                                    'medication_code': 'TEXT',
                                                    'medication_display': 'TEXT',
                                                    'subject_ref': 'TEXT',
                                                    'context_ref': 'TEXT',
                                                    'date_asserted': 'TIMESTAMP',
                                                    'information_source_ref': 'TEXT',
                                                    'note_text': 'TEXT'},
                                'grain': ['frappe_doc_name'],
                                'model_name': 'silver.medication_statement_fhir_resource',
                                'column_renames': {'id': 'fhir_id'}},
    'observation': {   'bronze_table': 'bronze.tabObservation_SatuSehat',
                       'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/observation.vd.json',
                       'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                                  'modified': 'TIMESTAMP',
                                                  'docstatus': 'INT',
                                                  'encounter_satusehat': 'TEXT',
                                                  'vital_signs': 'TEXT',
                                                  'patient': 'TEXT',
                                                  'patient_name': 'TEXT',
                                                  'patient_ihs': 'TEXT',
                                                  'practitioner_ihs': 'TEXT',
                                                  'satusehat_encounter_id': 'TEXT',
                                                  'validation_status': 'TEXT',
                                                  'satusehat_ids': 'TEXT'},
                       'passthrough_source': {   'frappe_doc_name': 'name',
                                                 'modified': 'modified',
                                                 'docstatus': 'docstatus',
                                                 'encounter_satusehat': 'encounter_satusehat',
                                                 'vital_signs': 'vital_signs',
                                                 'patient': 'patient',
                                                 'patient_name': 'patient_name',
                                                 'patient_ihs': 'patient_ihs',
                                                 'practitioner_ihs': 'practitioner_ihs',
                                                 'satusehat_encounter_id': 'satusehat_encounter_id',
                                                 'validation_status': 'validation_status',
                                                 'satusehat_ids': 'satusehat_ids'},
                       'is_array_payload': True,
                       'idx_column': 'observation_idx',
                       'fhir_columns': {   'fhir_id': 'TEXT',
                                           'status': 'TEXT',
                                           'category_code': 'TEXT',
                                           'code': 'TEXT',
                                           'code_display': 'TEXT',
                                           'subject_ref': 'TEXT',
                                           'encounter_ref': 'TEXT',
                                           'performer_ref': 'TEXT',
                                           'effective_datetime': 'TIMESTAMP',
                                           'value': 'DOUBLE',
                                           'unit': 'TEXT',
                                           'observation_idx': 'INT'},
                       'grain': ['frappe_doc_name', 'observation_idx'],
                       'model_name': 'silver.observation_fhir_resource',
                       'column_renames': {'id': 'fhir_id'}},
    'procedure': {   'bronze_table': 'bronze.tabProcedure_SatuSehat',
                     'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/procedure.vd.json',
                     'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                                'modified': 'TIMESTAMP',
                                                'docstatus': 'INT',
                                                'encounter_satusehat': 'TEXT',
                                                'clinical_procedure': 'TEXT',
                                                'patient_name': 'TEXT',
                                                'patient_ihs': 'TEXT',
                                                'practitioner_ihs': 'TEXT',
                                                'satusehat_encounter_id': 'TEXT',
                                                'satusehat_id': 'TEXT'},
                     'passthrough_source': {   'frappe_doc_name': 'name',
                                               'modified': 'modified',
                                               'docstatus': 'docstatus',
                                               'encounter_satusehat': 'encounter_satusehat',
                                               'clinical_procedure': 'clinical_procedure',
                                               'patient_name': 'patient_name',
                                               'patient_ihs': 'patient_ihs',
                                               'practitioner_ihs': 'practitioner_ihs',
                                               'satusehat_encounter_id': 'satusehat_encounter_id',
                                               'satusehat_id': 'satusehat_id'},
                     'is_array_payload': False,
                     'idx_column': None,
                     'fhir_columns': {   'fhir_id': 'TEXT',
                                         'status': 'TEXT',
                                         'category_code': 'TEXT',
                                         'code': 'TEXT',
                                         'code_display': 'TEXT',
                                         'subject_ref': 'TEXT',
                                         'encounter_ref': 'TEXT',
                                         'performer_ref': 'TEXT'},
                     'grain': ['frappe_doc_name'],
                     'model_name': 'silver.procedure_fhir_resource',
                     'column_renames': {'id': 'fhir_id'}},
    'questionnaire_response': {   'bronze_table': 'bronze.tabQuestionnaireResponse_SatuSehat',
                                  'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/questionnaire_response.vd.json',
                                  'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                                             'modified': 'TIMESTAMP',
                                                             'docstatus': 'INT',
                                                             'encounter_satusehat': 'TEXT',
                                                             'patient_name': 'TEXT',
                                                             'patient_ihs': 'TEXT',
                                                             'practitioner_ihs': 'TEXT',
                                                             'satusehat_encounter_id': 'TEXT',
                                                             'keluhan_utama': 'TEXT',
                                                             'riwayat_alergi': 'INT',
                                                             'satusehat_id': 'TEXT'},
                                  'passthrough_source': {   'frappe_doc_name': 'name',
                                                            'modified': 'modified',
                                                            'docstatus': 'docstatus',
                                                            'encounter_satusehat': 'encounter_satusehat',
                                                            'patient_name': 'patient_name',
                                                            'patient_ihs': 'patient_ihs',
                                                            'practitioner_ihs': 'practitioner_ihs',
                                                            'satusehat_encounter_id': 'satusehat_encounter_id',
                                                            'keluhan_utama': 'keluhan_utama',
                                                            'riwayat_alergi': 'riwayat_alergi',
                                                            'satusehat_id': 'satusehat_id'},
                                  'is_array_payload': False,
                                  'idx_column': None,
                                  'fhir_columns': {   'fhir_id': 'TEXT',
                                                      'status': 'TEXT',
                                                      'questionnaire': 'TEXT',
                                                      'subject_ref': 'TEXT',
                                                      'encounter_ref': 'TEXT',
                                                      'authored': 'TIMESTAMP',
                                                      'author_ref': 'TEXT',
                                                      'source_ref': 'TEXT'},
                                  'grain': ['frappe_doc_name'],
                                  'model_name': 'silver.questionnaire_response_fhir_resource',
                                  'column_renames': {'id': 'fhir_id'}},
    'service_request': {   'bronze_table': 'bronze.tabServiceRequest_SatuSehat',
                           'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/service_request.vd.json',
                           'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                                      'modified': 'TIMESTAMP',
                                                      'docstatus': 'INT',
                                                      'encounter_satusehat': 'TEXT',
                                                      'patient_name': 'TEXT',
                                                      'patient_ihs': 'TEXT',
                                                      'practitioner_ihs': 'TEXT',
                                                      'satusehat_encounter_id': 'TEXT',
                                                      'satusehat_id': 'TEXT'},
                           'passthrough_source': {   'frappe_doc_name': 'name',
                                                     'modified': 'modified',
                                                     'docstatus': 'docstatus',
                                                     'encounter_satusehat': 'encounter_satusehat',
                                                     'patient_name': 'patient_name',
                                                     'patient_ihs': 'patient_ihs',
                                                     'practitioner_ihs': 'practitioner_ihs',
                                                     'satusehat_encounter_id': 'satusehat_encounter_id',
                                                     'satusehat_id': 'satusehat_id'},
                           'is_array_payload': False,
                           'idx_column': None,
                           'fhir_columns': {   'fhir_id': 'TEXT',
                                               'identifier_value': 'TEXT',
                                               'status': 'TEXT',
                                               'intent': 'TEXT',
                                               'category_code': 'TEXT',
                                               'code': 'TEXT',
                                               'code_display': 'TEXT',
                                               'subject_ref': 'TEXT',
                                               'encounter_ref': 'TEXT',
                                               'authored_on': 'TIMESTAMP',
                                               'requester_ref': 'TEXT',
                                               'performer_ref': 'TEXT'},
                           'grain': ['frappe_doc_name'],
                           'model_name': 'silver.service_request_fhir_resource',
                           'column_renames': {'id': 'fhir_id'}},
    'specimen': {   'bronze_table': 'bronze.tabSpecimen_SatuSehat',
                    'vd_path': '/home/playground-magang/lakehouse/models_dependencies/views/specimen.vd.json',
                    'passthrough_columns': {   'frappe_doc_name': 'TEXT',
                                               'modified': 'TIMESTAMP',
                                               'docstatus': 'INT',
                                               'encounter_satusehat': 'TEXT',
                                               'servicerequest_satusehat': 'TEXT',
                                               'patient_name': 'TEXT',
                                               'patient_ihs': 'TEXT',
                                               'practitioner_ihs': 'TEXT',
                                               'satusehat_id': 'TEXT'},
                    'passthrough_source': {   'frappe_doc_name': 'name',
                                              'modified': 'modified',
                                              'docstatus': 'docstatus',
                                              'encounter_satusehat': 'encounter_satusehat',
                                              'servicerequest_satusehat': 'servicerequest_satusehat',
                                              'patient_name': 'patient_name',
                                              'patient_ihs': 'patient_ihs',
                                              'practitioner_ihs': 'practitioner_ihs',
                                              'satusehat_id': 'satusehat_id'},
                    'is_array_payload': False,
                    'idx_column': None,
                    'fhir_columns': {   'fhir_id': 'TEXT',
                                        'identifier_value': 'TEXT',
                                        'status': 'TEXT',
                                        'type_code': 'TEXT',
                                        'subject_ref': 'TEXT',
                                        'request_ref': 'TEXT',
                                        'collected_datetime': 'TIMESTAMP',
                                        'collector_ref': 'TEXT'},
                    'grain': ['frappe_doc_name'],
                    'model_name': 'silver.specimen_fhir_resource',
                    'column_renames': {'id': 'fhir_id'}}}
