MODEL (
  name bronze.tabItem,
  kind INCREMENTAL_BY_TIME_RANGE (
    time_column modified
  ),
  grain ('name', 'modified'),
);

-- Bridge ke MariaDB via DuckDB Quack server (lihat analytics-bridge repo).
-- IF NOT EXISTS supaya aman kalau session yang sama sudah pernah attach.
ATTACH IF NOT EXISTS 'quack:localhost:9494' AS frappe_bridge (
    TYPE quack,
    TOKEN @quack_token(),
    DISABLE_SSL true
);

-- Bronze = raw & complete: explicit mapping based on dump.json
SELECT
  name::VARCHAR AS name,
  creation::TIMESTAMP AS creation,
  modified::TIMESTAMP AS modified,
  modified_by::VARCHAR AS modified_by,
  owner::VARCHAR AS owner,
  docstatus::INTEGER AS docstatus,
  idx::INTEGER AS idx,
  naming_series::VARCHAR AS naming_series,
  item_code::VARCHAR AS item_code,
  item_name::VARCHAR AS item_name,
  item_group::VARCHAR AS item_group,
  stock_uom::VARCHAR AS stock_uom,
  disabled::INTEGER AS disabled,
  allow_alternative_item::INTEGER AS allow_alternative_item,
  is_stock_item::INTEGER AS is_stock_item,
  has_variants::INTEGER AS has_variants,
  opening_stock::DECIMAL(21,9) AS opening_stock,
  valuation_rate::DECIMAL(21,9) AS valuation_rate,
  standard_rate::DECIMAL(21,9) AS standard_rate,
  is_fixed_asset::INTEGER AS is_fixed_asset,
  auto_create_assets::INTEGER AS auto_create_assets,
  is_grouped_asset::INTEGER AS is_grouped_asset,
  asset_category::VARCHAR AS asset_category,
  asset_naming_series::VARCHAR AS asset_naming_series,
  over_delivery_receipt_allowance::DECIMAL(21,9) AS over_delivery_receipt_allowance,
  over_billing_allowance::DECIMAL(21,9) AS over_billing_allowance,
  image::VARCHAR AS image,
  description::VARCHAR AS description,
  brand::VARCHAR AS brand,
  shelf_life_in_days::INTEGER AS shelf_life_in_days,
  end_of_life::DATE AS end_of_life,
  default_material_request_type::VARCHAR AS default_material_request_type,
  valuation_method::VARCHAR AS valuation_method,
  warranty_period::VARCHAR AS warranty_period,
  weight_per_unit::DECIMAL(21,9) AS weight_per_unit,
  weight_uom::VARCHAR AS weight_uom,
  allow_negative_stock::INTEGER AS allow_negative_stock,
  has_batch_no::INTEGER AS has_batch_no,
  create_new_batch::INTEGER AS create_new_batch,
  batch_number_series::VARCHAR AS batch_number_series,
  has_expiry_date::INTEGER AS has_expiry_date,
  retain_sample::INTEGER AS retain_sample,
  sample_quantity::INTEGER AS sample_quantity,
  has_serial_no::INTEGER AS has_serial_no,
  serial_no_series::VARCHAR AS serial_no_series,
  variant_of::VARCHAR AS variant_of,
  variant_based_on::VARCHAR AS variant_based_on,
  enable_deferred_expense::INTEGER AS enable_deferred_expense,
  no_of_months_exp::INTEGER AS no_of_months_exp,
  enable_deferred_revenue::INTEGER AS enable_deferred_revenue,
  no_of_months::INTEGER AS no_of_months,
  purchase_uom::VARCHAR AS purchase_uom,
  min_order_qty::DECIMAL(21,9) AS min_order_qty,
  safety_stock::DECIMAL(21,9) AS safety_stock,
  is_purchase_item::INTEGER AS is_purchase_item,
  lead_time_days::INTEGER AS lead_time_days,
  last_purchase_rate::DECIMAL(21,9) AS last_purchase_rate,
  is_customer_provided_item::INTEGER AS is_customer_provided_item,
  customer::VARCHAR AS customer,
  delivered_by_supplier::INTEGER AS delivered_by_supplier,
  country_of_origin::VARCHAR AS country_of_origin,
  customs_tariff_number::VARCHAR AS customs_tariff_number,
  sales_uom::VARCHAR AS sales_uom,
  grant_commission::INTEGER AS grant_commission,
  is_sales_item::INTEGER AS is_sales_item,
  max_discount::DECIMAL(21,9) AS max_discount,
  inspection_required_before_purchase::INTEGER AS inspection_required_before_purchase,
  quality_inspection_template::VARCHAR AS quality_inspection_template,
  inspection_required_before_delivery::INTEGER AS inspection_required_before_delivery,
  include_item_in_manufacturing::INTEGER AS include_item_in_manufacturing,
  is_sub_contracted_item::INTEGER AS is_sub_contracted_item,
  default_bom::VARCHAR AS default_bom,
  customer_code::VARCHAR AS customer_code,
  default_item_manufacturer::VARCHAR AS default_item_manufacturer,
  default_manufacturer_part_no::VARCHAR AS default_manufacturer_part_no,
  total_projected_qty::DECIMAL(21,9) AS total_projected_qty,
  _user_tags::VARCHAR AS _user_tags,
  _comments::VARCHAR AS _comments,
  _assign::VARCHAR AS _assign,
  _liked_by::VARCHAR AS _liked_by,
  kfa_code::VARCHAR AS kfa_code,
  kfa_display::VARCHAR AS kfa_display,
  satusehat_id::VARCHAR AS satusehat_id
FROM frappe_bridge.bridge.tabitem
WHERE modified >= @start_ds AND modified < @end_ds;
